name: DJD
favicon: null
layout_spectrum: 0.5483700844924897
typography_spectrum: 0.3492246351670474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.31559354928322136
  lightness: 0.7322972796391696
  saturation: 0.12350049917586148
  rhythmicContrast: 0.7256210055202246
purpose: []
